task_list = { task* }
task = { priority ~ WHITE_SPACE ~ status ~ WHITE_SPACE ~ date ~ WHITE_SPACE ~ description }

priority = { "!"{1,3} }
status = { "[" ~ ("x" | WHITE_SPACE) ~ "]" }

date = { "{" ~ year ~ "-" ~ month ~ "-" ~ day ~ "}" }
year = { ASCII_DIGIT{4} }
month = { "0" ~ '1'..'9' | "1" ~ '0'..'2' }
day = { "0" ~ '1'..'9' | '1'..'2' ~ ASCII_DIGIT | "3" ~ '0'..'1' }

description = { (ASCII_ALPHANUMERIC | " ")+ }

